- name: Install packages
  ansible.builtin.apt:
    name:
      - python3-certbot-nginx

- name: Create SSL
  ansible.builtin.command:
    cmd: "certbot certonly --nginx --agree-tos -n -m {{ certbot_email }} -d {{ certbot_domain }}"
    creates: "/etc/letsencrypt/live/{{ certbot_domain }}/privkey.pem"
